plugins {
    id 'java'
    // Plugin Allure để tạo báo cáo test UI
    id 'io.qameta.allure' version '2.11.2'

    // Plugin OWASP Dependency-Check để quét SCA (Bảo mật thư viện)
    id "org.owasp.dependencycheck" version "9.0.9"
}

group 'org.example'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation group: 'org.testng', name: 'testng', version: '7.7.1'
    implementation group: 'io.github.bonigarcia', name: 'webdrivermanager', version: '5.9.2'
    implementation group: 'org.seleniumhq.selenium', name: 'selenium-java', version: '4.21.0'
    implementation group: 'com.googlecode.json-simple', name: 'json-simple', version: '1.1.1'
    implementation group: 'com.github.javafaker', name: 'javafaker', version: '1.0.2'
    implementation group: 'org.apache.logging.log4j', name: 'log4j-core', version: '2.19.0'
    implementation group: 'org.apache.logging.log4j', name: 'log4j-api', version: '2.19.0'
    implementation group: 'io.qameta.allure', name: 'allure-testng', version: '2.18.1'
    implementation group: 'org.slf4j', name: 'log4j-over-slf4j', version: '2.0.6'
}

test {
    if(project.hasProperty("username") && project.hasProperty("password")) {
        systemProperties.put("username", project.property("username"))
        systemProperties.put("password", project.property("password"))
    }

    useTestNG() {
        suites "/src/test/resources/test.xml"
    }

    testLogging {
        events "passed", "skipped", "failed"
        showStandardStreams = true
        exceptionFormat = 'full'
    }
}

allure {
    version = '2.18.1'
}

// --- PHẦN SỬA ĐỔI ĐỂ CHỐNG LỖI 403 VÀ TREO PIPELINE ---
dependencyCheck {
    // Điểm CVSS > 7.0 sẽ đánh rớt Pipeline nếu quét thành công
    failBuildOnCVSS = 7.0
    formats = ['HTML', 'XML']

    // CỰC KỲ QUAN TRỌNG: Nếu lỗi kết nối NVD (403/404), vẫn cho phép chạy tiếp stage sau
    failOnError = false

    nvd {
        apiKey = "880D9B94-5F33-F111-8369-129478FCB64D"

        // Tăng thời gian giãn cách gọi API để tránh bị NVD chặn (tính bằng mili giây)
        // 16000ms = 16 giây, mức an toàn nhất cho Jenkins/Docker
        delay = 16000
    }
}