plugins {
    id 'java'
    // Them plugin allure de tao bao cao dep nhu cua thay
    id 'io.qameta.allure' version '2.11.2'

    // --- THÊM MỚI BƯỚC 2 (SCA): Khai báo plugin OWASP Dependency-Check ---
    id "org.owasp.dependencycheck" version "9.0.9"
}

group 'org.example'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation group: 'org.testng', name: 'testng', version: '7.7.1'
    implementation group: 'io.github.bonigarcia', name: 'webdrivermanager', version: '5.9.2'
    implementation group: 'org.seleniumhq.selenium', name: 'selenium-java', version: '4.21.0'
    implementation group: 'com.googlecode.json-simple', name: 'json-simple', version: '1.1.1'
    implementation group: 'com.github.javafaker', name: 'javafaker', version: '1.0.2'
    implementation group: 'org.apache.logging.log4j', name: 'log4j-core', version: '2.19.0'
    implementation group: 'org.apache.logging.log4j', name: 'log4j-api', version: '2.19.0'
    implementation group: 'io.qameta.allure', name: 'allure-testng', version: '2.18.1'
    implementation group: 'org.slf4j', name: 'log4j-over-slf4j', version: '2.0.6'
}

test {
    if(project.hasProperty("username") && project.hasProperty("password")) {
        systemProperties.put("username", project.property("username"))
        systemProperties.put("password", project.property("password"))
    }

    useTestNG() {
        suites "/src/test/resources/test.xml"
    }

    // --- DOAN CODE NAY GIUP JENKINS IN KET QUA TUNG BAI TEST ---
    testLogging {
        events "passed", "skipped", "failed"
        showStandardStreams = true
        exceptionFormat = 'full'
    }
}

// Cau hinh Allure Report
allure {
    version = '2.18.1'
}

// --- THÊM MỚI BƯỚC 2 (SCA): Cấu hình luật cho OWASP Dependency-Check ---
dependencyCheck {
    // Điểm CVSS từ 0 đến 10. Mình cài > 7.0 (nghĩa là phát hiện lỗi Nghiêm trọng/Cao) thì đánh rớt Pipeline
    failBuildOnCVSS = 7.0
    // Xuất báo cáo ra định dạng HTML để bạn có thể tải về nộp cho thầy xem
    formats = ['HTML', 'XML']

    // Thêm thẻ nvd và dán API Key của bạn vào đây
    nvd {
        apiKey = "880D9B94-5F33-F111-8369-129478FCB64D"
    }
}